config/routes.rb
AppMiniBank2::Application.routes.draw do
  root to: 'sessions#new'
  resources :sessions

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  resources :clients do
   resources :accounts
  end


  resources :accounts do
   resources :transactions
  end



end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :client
  has_many :transactions, dependent:  :destroy

  validates :balance, numericality: { only_integer: true}

  before_create :set_number

  def to_s
    "[#{number}] #{balance} zl"
  end

  def update_balance!
    sum = transactions.map { |t| t.amount }.sum
    update_attribute(:balance, sum)
  end

  protected
  def set_number
    self.number = rand 1_000_000_000
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :accounts

  has_secure_password

  validates :name, :surname, length: {minimum: 2}
  validates :email, format: {with: /\A.+@.+\z/}
  validates :phone, format: {with: /\d{3}-\d{3}-\d{3}\z/}


  def to_s
    "#{name} #{surname} (#{id})"
  end



end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account

  after_save :update_account_balance

  validates :descr, presence: true
  validates :amount, numericality: { only_integer: true }


  protected
  def update_account_balance
    account.update_balance!
  end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :find_client
  before_filter :find_account, only: [:show, :destroy]

  def index
    @accounts = @client.accounts.order('id').page(params[:page])
  end

  def show

  end

  def create
    @client.accounts.create!
    redirect_to client_accounts_path(@client)
  end

  def destroy
    @account.destroy
    redirect_to client_accounts_path(@client)
  end

  private
  def find_client
    @client = Client.find(params[:client_id])
  end

  def find_account
    @account = @client.accounts.find(params[:id])
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :auth!

  protected
  def current_client
     @current_client ||= Client.find(session[:client_id]) if session[:client_id]
  end

  helper_method :current_client
  def auth!
    if current_client.nil?
      redirect_to login_path, alert: 'Prosze sie zalogowac!'
    end
  end



end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  skip_before_filter :auth!, only: [:new, :create]
  before_filter :deny, except: [:new, :create]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.page(params[:page])
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

      if @client.save
        ClientMailer.welcome(@client).deliver
        redirect_to login_path, notice: 'Prosze sie zalogowac.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /clients/1
    # PATCH/PUT /clients/1.json
    def update
      respond_to do |format|
        if @client.update(client_params)
          format.html { redirect_to @client, notice: 'Client was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @client.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /clients/1
    # DELETE /clients/1.json
    def destroy
      @client.destroy
      respond_to do |format|
        format.html { redirect_to clients_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :surname, :email, :phone,
                                     :password, :password_confirmation)
    end

    def deny
      raise 'Ups!!!'
    end


  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :auth!, only: [:new, :create]

  def new
  end

  def create
    client = Client.find_by_email(params[:email])
    if client && client.authenticate(params[:password])
      session[:client_id] = client.id
      redirect_to client_accounts_path(client), notice: 'Witamy'
    else
      flash.now.alert = 'Niestety'
      render action: 'new'
    end
  end

  def destroy
    session[:client_id] = nil
    redirect_to root_path, notice: 'Do zobaczenia...'
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_filter :find_account


  def index
    @transactions = @account.transactions.order('id desc').page(params[:page])
  end


  def new
    @transaction = @account.transactions.new
  end

  def create
    @transaction = @account.transactions.new(transaction_params)
    if @transaction.save
      msg = 'Transakaja zapisana pomyślnie'
      redirect_to account_transactions_path(@account), notice: msg
    else
      render action: 'new'
    end
  end

  private
  def find_account
    @account = Account.find(params[:account_id])
    @client = @account.client
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :descr)
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def money(amount, currency='zl')
    "#{amount} #{currency}"
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_account.html.haml
%tr
   %td= account.number
   %td= account.balance
   %td= link_to 'Show',[@client,account]
   %td= link_to 'Destroy',[@client,account], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/accounts/index.html.haml
= content_for :client, @client

%h1 Lista kont klienta

%table.table
  %tr
    %th Numer
    %th Saldo
    %th
    %th

  = render @accounts

%br

%p= paginate @accounts

= link_to 'New Account', client_accounts_path(@client), class: 'btn', :method =>:post

app/views/accounts/show.html.haml
%h2= @account


%p= link_to 'Lista transakcji', account_transactions_path(@account), class: 'btn'

app/views/clients/_form.html.haml
= form_for @client do |f|
  - if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/clients/edit.html.haml
%h1 Editing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
%h1 Listing clients

%table.table
  %tr
    %th Name
    %th Surname
    %th Email
    %th Phone
    %th
    %th
    %th

  - @clients.each do |client|
    %tr
      %td= client.name
      %td= client.surname
      %td= client.email
      %td= client.phone
      %td= link_to 'Show', client
      %td= link_to 'Edit', edit_client_path(client)
      %td= link_to 'Destroy', client, :method => :delete, :data => { :confirm => 'Are you sure?' }


%p= paginate @clients

%br

= link_to 'New Client', new_client_path, class: 'btn'

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.haml
= content_for :client, @client

%p

%p
  %b Name:
  = @client.name
%p
  %b Surname:
  = @client.surname
%p
  %b Email:
  = @client.email
%p
  %b Phone:
  = @client.phone

= link_to 'Edit', edit_client_path(@client)
\|
= link_to 'Back', clients_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppMiniBank2</title>
  <meta name="viewport" content="width=device=width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
      body {
          padding-top: 60px; /* 60px to make the contianer go all the way to the boottom of the topbar */

      }
  </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse"
              data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">MinibankApp</a>
      <% if current_client%>
        <a class="brand" href="#"><%= yield :client %></a>
      <% end %>

      <div class="nav-collapse collapse">
        <% if @client && !@client.new_record? %>
            <ul class="nav">
              <li><%= link_to 'Konta', client_accounts_path(@client)  %></li>
              <li><%= link_to 'Wyloguj', logout_path %></li>
            </ul>
        <% end %>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <% if notice.present? %><p class="alert alert-success"><%= notice %></p>
      <% end %>
  <% if alert.present? %><p class="alert alert-success"><%= alert %></p>
      <% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/transactions/index.html.haml
%p= link_to 'Dodaj transakcje', new_account_transaction_path(@account), class: 'btn'

%table.table
  %tr
    %th Data
    %th Kwota
    %th Opis
  - @transactions.each do |transaction|
    %tr
      %td= I18n.l transaction.created_at
      %td= money(transaction.amount)
      %td= transaction.descr

%p= paginate @transactions

app/views/transactions/new.html.haml
%h2 Nowa transakcja

= form_for [@account, @transaction] do |f|
  .field
  = f.label :amount
  = f.text_field :amount
  .field
  = f.label :descr
  = f.text_field :descr
  = f.submit 'Zapisz'